baseURL: /
languageCode: en-us
title: "APIzation: Replication Package"
theme: anubis

menu:
  main:
    - identifier: study
      name: ğŸ“Š Study on APIzations
      url: /study/
      weight: 1
    - identifier: evaluation
      name: ğŸ“ Evaluation of the approach
      url: /evaluation/
      weight: 2
    - identifier: search
      name: ğŸ” Search APIzations
      url: /search/
      weight: 3

params:
  author: "Pasquale Salza"
  customCss:
    - custom.css
  style: light-without-switcher

markup:
  goldmark:
    renderer:
      unsafe: true
